# Generated by Django 5.2.3 on 2025-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_itemcarrinho_adicionado_em_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('percentual_desconto', models.FloatField()),
                ('ativa', models.BooleanField(default=True)),
                ('produtos', models.ManyToManyField(to='loja.produto')),
            ],
        ),
    ]
