# Generated by Django 5.2.3 on 2025-06-19 18:25

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=products.models.generate_sku, max_length=5, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Completa')),
                ('short_description', models.CharField(max_length=150, verbose_name='Descrição Curta')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridade de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do Produto')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('categories', models.ManyToManyField(related_name='products', to='products.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
