# Generated by Django 5.2.3 on 2025-06-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Processando', 'Processando'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status do Pedido')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('shipping_address', models.TextField(verbose_name='Endereço de Entrega')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Reembolsado', 'Reembolsado'), ('Falha', 'Falha')], default='Pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização do Pedido')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nome do Produto (Histórico)')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço na Compra')),
                ('total_item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total do Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
